---
- name: "Install apache webservers"
  hosts: web8s
  vars:
    pckg_name: nginx
    html_message: "This is My First Nginx Web Server with ansible"
    doc_root: "/usr/share/nginx/html"
  become: yes
  tasks:
    - name: Install epel-release repo
      yum:
        name: epel-release
        state: present
      when: pckg_name == "nginx"
      
    - name: Installing a package
      yum:
        name: "{{ pckg_name }}"
        state: present

    - name: Start and enable a service
      service:
        name: "{{ pckg_name }}"
        state: started
        enabled: yes

    - name: Add firewall rule
      firewalld:
        state: enabled
        service: http
        permanent: yes
        immediate: yes
        
    - name: Add index.hmtl file
      copy:
        dest: "{{ doc_root }}/index.html"
        content: "{{ html_message }}"
