---
- name: "Install apache webservers"
  hosts: web7s
  become: yes
  tasks:
    - name: Installing a package
      yum:
        name: httpd
        state: present

    - name: Start and enable a service
      service:
        state: started
        name: httpd
        enabled: yes

    - name: 'Restarting firewalld'
      systemd:
        name: firewalld
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Add firewall rule
      firewalld:
        state: enabled
        service: http
        permanent: yes
        immediate: yes

    - name: Add index.hmtl file
      copy:
        dest: /var/www/html/index.html
        content: "This is a list webserver we created with ansible"